name: silkjam
services:
  silkjam:
    build: .
    image: silkjam:latest
    container_name: silkjam
    ports:
      - 8500:8000
    volumes:
      - data:/app/data
    environment:
      - ENV=dev
    restart: unless-stopped
volumes:
  data:
