name: silkjam
services:
  silkjam:
    build: .
    image: silkjam:latest
    container_name: silkjam
    ports:
      - ${API_PORT:-8000}:8000
      - ${MINECRAFT_PORT:-25565}:25565  # Expose Minecraft port
    volumes:
      - data:/app/data
    environment:
      - HOSTNAME=${HOSTNAME:-localhost}  # Domain name
    restart: unless-stopped
volumes:
  data:
