from typing import Any, Self

class AsyncPINGClient:
    def __init__(self, host: str, port: int, *args: Any, **kwargs: Any) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, *args: Any) -> None: ...
    async def ping(self) -> Any: ...
    async def get_stats(self) -> dict[str, Any]: ...

class AsyncRCONClient:
    def __init__(self, host: str, port: int, *args: Any, **kwargs: Any) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, *args: Any) -> None: ...
    async def login(self, password: str) -> Any: ...
    async def command(self, command: str) -> str: ...